### ISSUE TITLE
Support Own Trades messages

### ISSUE THREAD

**Issue by m4cx** [m4cx/kraken-wsapi-dotnet#39]
[ownTrades](https://www.kraken.com/features/websocket-api-beta#message-ownTrades) 

Publication: Own trades, on subscription last 50 trades for the user will be sent, followed by new trades.

**Comment by R00iBaard** [comment]
Hey,

Just want to say thanks so so much for this lib - Its really epic! Just wanted to get an update on this. Is this branch operational? Or are we close to getting this merged into master and/or Nuget Package manager?

**Comment by m4cx** [comment]
This branch is still operational, but unfortunately I was not able to work on this issue in the past weeks. My current plan is to provide it as soon as possible. I guess, that I will make it until next weekend.

**Comment by R00iBaard** [comment]
Hey,

So I am using the feature/own-trades code base to handle both public and private in the mean time. Its working fine as far as I can tell. Just rather confused what wss://ws-sandbox.kraken.com in particular is? Any reason I cant connect using ws-auth.kraken.com?

I am using both public and private as follows :

            using (var clientPublic = KrakenApi.ClientFactory.Create("wss://ws.kraken.com"))
            using (var clientPrivate = KrakenApi.ClientFactory.Create("wss://ws-auth.kraken.com"))
            {
                var res = await CoreManager.krakenManager.GetWebSocketToken();
                Task.Run(() => RunKrakenPublic(clientPublic));
                Task.Run(() => RunKrakenPrivate(clientPrivate, res.token));
                do
                {
                    Console.WriteLine("Press [ESC] to exit.");
                }
                while (Console.ReadKey().Key != ConsoleKey.Escape);
            }

**Comment by m4cx** [comment]
I will check the described endpoint "wss://ws-auth.kraken.com". Haven't tried it so far. In order to be more clear on the reaction I will try to give a more detailed output for the user of the library. 

Have you checkeds, that the endpoint Is physically availble?

**Comment by R00iBaard** [comment]
Yeah, see below... unless they dont allow ping requests?

![Capture](https://user-images.githubusercontent.com/11412240/66480300-a1b16280-ea9e-11e9-9531-a6c4a730ad3b.PNG)

Then lastly, when I use my actual token via the https://api.kraken.com/0/private/GetWebSocketsToken API I dont receive the last 50 trades even though I connect fine. However when using the following 
YXBpS2V5NDMyOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA== I receive the last 50 trades.

**Comment by m4cx** [comment]
Then it seems to me the documentation is somehow misleading on the kraken.com side. Have you tried to connect to private messages via the normal websocket uri `wss://ws.kraken.com`?

**Comment by R00iBaard** [comment]
Ah, sorry thought that endpoint was only for public messaging. Anyway I can connect and subscribe but dont receive any IncomingMessage for owntrades.

**Comment by R00iBaard** [comment]
All sorted :) 

using (var clientPrivate = KrakenApi.ClientFactory.Create("wss://beta-ws.kraken.com/")) 

Didnt know beta-ws allowed private transactions - https://support.kraken.com/hc/en-us/articles/360034664311

**Comment by m4cx** [comment]
So the private information is still in beta? I wasn't aware of this ...

**Comment by drmrboyc** [comment]
R00iBaard, I came here to ask Maik how he was getting access to the private websockets, and you already found it! Thanks :)

I've been using this great lib from Maik for almost a year, and I ended up forking it a few weeks ago specifically to add ownTrades, openOrders, and ping/pong, but once I got it all coded, the auth-ws.kraken.com endpoint wasn't working! Kraken support told me that they hadn't "officially" launched private websockets and that it was a few weeks from beta. So I've just been sitting on it until I received notices about this thread, where it appeared that Maik was successfully sending and receiving private websocket data. Lo and behold...they finally launched the beta!

Kraken also told me that they were going to be extensively updating and reworking the API documentation, so I imagine that the TA about beta access to private websockets is fairly new. Thanks again for the heads up R00iBaard!

Maik, I was gonna throw a pull request your way as I did my best to keep your framework and methodology when adding those features. I figured if there was anything you liked from my spaghetti, it might save you some time. But it looks like you've already got it figured out, and your code is very usable and well structured, I'd hate to throw poppycock into the mix. So I'll just wait until you merge the master branch and update my fork with your awesomeness xD.

**Comment by m4cx** [comment]
@drmrboyc I really appreciate your feedback. But I would also be interested in your solution.

**Comment by drmrboyc** [comment]
@m4cx If you'd like I can push all my crazy code to my fork once I finish getting the private websocket messages working. If you happen to have a little time, I have a couple questions. I was going to figure it all out once the ws-auth endpoint became available, but maybe you'd be willing to provide some insight.

**1.** My first question is concerning deserializing the ownTrades and openOrders payloads because they uses labels in the JSON.

I figured that because Kraken's private messages are more like DataMessages in their content, I would implement them the same way as how you do the other DataMessages. On the other hand, their payloads have labels in the JSON, which is how a KrakenMessage (event) is provided. You created KrakenMessageSerializer to assimilate specifically events into their arg objects. So, I wasn't sure which implementation was better...to just reference the JArray by label/position or if it was better to use your Serializer. I decided that using the serializer (or even making a new one) could cause more confusion or redundancy.

I implemented the ownTrades messages similar to how you did TradesMessage and TradeValues. OwnTradesMessage is like a Data Message which uses CreateFromString to deserialize the JSON into the class properties. Inside OwnTradesMessage.CreateFromString it calls OwnTradeValues.CreateFromJArray which deserializes each trade. I reference the tokens by labels instead of token placement in the JArray because the websocket documentation shows varying token placement, and I haven't been able to actually see a payload yet.

In the context of using your existing structure, do you think that's the best way to handle deserializing the private payloads?

**2.** My next question is about openOrders. It uses labels like ownTrades, so I handle it the same way. However, the payload nests 3 levels, Order -> Description -> Value. To handle this would you use 3 classes? Something like OpenOrdersMessage / OpenOrderValues / OpenOrderDescriptionValues? It seems like this would most closely emulate your framework, but I wasn't sure if you had a better idea in mind or already programmed.

**3.** Finally, my last question is about the openOrders status-change payload. Using the method from my previous question, openOrders would need two more classes as well OpenOrdersUpdateMessage & OpenOrderUpdateValues. That's similar to how you implemented BookUpdateMessage & PriceLevel. However, there appears to be only one token in each openOrderUpdate order, "status". In the websocket documentation there's only one type of status-change "closed". In the REST documentation we see "pending", "open", "closed", "canceled", and "expired". So my question is how would you want this implemented? With two classes (message & values), or one class that creates the array of orders and gives each an id and status. Two classes seems unnecessarily excessive, but also a better option if that payload ends up with more properties in the future. Ultimately, I used two classes, but you may have already thought of a better way to implement openOrders.

Sorry for the wall of text. You have a much better understanding of object-oriented design than I do, so I didn't want to waste your time with a pull that's just junk. xD

**Comment by m4cx** [comment]
Yeah... I would love to look at your changes. Please push them to your repository. There is no need for a PR, if you are insecure about the benefit.

Regarding your questions. The serializer was a first step into deserializing the contents. But having seen that many changes in the several message types it is hard to get the configuration right. I want to keep it as simple as possible for now. 

That is why I switched to the explicit implementation you see in the DataMessages. When the project gets mature, I will try to refactor it. 

Your approach seems to fit so far.

**Comment by m4cx** [comment]
#46

**Comment by m4cx** [comment]
Please try out the current pre-release package with the current support of ownTrades:
https://www.nuget.org/packages/Kraken.WebSockets/0.4.0-b369
